# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: G4_Audio.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'G4_Audio.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eG4_Audio.proto\x12\x08G4_Audio\"\x11\n\x0flistaCancionesS\")\n\x0flistaCancionesR\x12\x16\n\x0elistaCanciones\x18\x01 \x03(\t\"\x1d\n\nmetadatosS\x12\x0f\n\x07\x61rchivo\x18\x01 \x01(\t\"y\n\nmetadatosR\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x11\n\tcodecName\x18\x02 \x01(\t\x12\x12\n\nsampleRate\x18\x03 \x01(\x05\x12\x0f\n\x07\x63\x61nales\x18\x04 \x01(\x05\x12\x10\n\x08\x64uracion\x18\x05 \x01(\x02\x12\x0f\n\x07\x62itRate\x18\x06 \x01(\x05\"\x1b\n\x08\x63\x61ncionS\x12\x0f\n\x07\x61rchivo\x18\x01 \x01(\t\"\x1c\n\x08\x63\x61ncionR\x12\x10\n\x08\x63\x61ncionB\x18\x01 \x01(\x0c\x32\xcc\x01\n\x05\x41udio\x12I\n\x11getListaCanciones\x12\x19.G4_Audio.listaCancionesS\x1a\x19.G4_Audio.listaCancionesR\x12:\n\x0cgetMetadatos\x12\x14.G4_Audio.metadatosS\x1a\x14.G4_Audio.metadatosR\x12<\n\x0egetStreamAudio\x12\x12.G4_Audio.cancionS\x1a\x12.G4_Audio.cancionR(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'G4_Audio_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LISTACANCIONESS']._serialized_start=28
  _globals['_LISTACANCIONESS']._serialized_end=45
  _globals['_LISTACANCIONESR']._serialized_start=47
  _globals['_LISTACANCIONESR']._serialized_end=88
  _globals['_METADATOSS']._serialized_start=90
  _globals['_METADATOSS']._serialized_end=119
  _globals['_METADATOSR']._serialized_start=121
  _globals['_METADATOSR']._serialized_end=242
  _globals['_CANCIONS']._serialized_start=244
  _globals['_CANCIONS']._serialized_end=271
  _globals['_CANCIONR']._serialized_start=273
  _globals['_CANCIONR']._serialized_end=301
  _globals['_AUDIO']._serialized_start=304
  _globals['_AUDIO']._serialized_end=508
# @@protoc_insertion_point(module_scope)
