# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import G4_Audio_pb2 as G4__Audio__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in G4_Audio_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AudioStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.getListaCanciones = channel.unary_unary(
                '/G4_Audio.Audio/getListaCanciones',
                request_serializer=G4__Audio__pb2.listaCancionesS.SerializeToString,
                response_deserializer=G4__Audio__pb2.listaCancionesR.FromString,
                _registered_method=True)
        self.getMetadatos = channel.unary_unary(
                '/G4_Audio.Audio/getMetadatos',
                request_serializer=G4__Audio__pb2.metadatosS.SerializeToString,
                response_deserializer=G4__Audio__pb2.metadatosR.FromString,
                _registered_method=True)
        self.getStreamAudio = channel.stream_stream(
                '/G4_Audio.Audio/getStreamAudio',
                request_serializer=G4__Audio__pb2.cancionS.SerializeToString,
                response_deserializer=G4__Audio__pb2.cancionR.FromString,
                _registered_method=True)


class AudioServicer(object):
    """Missing associated documentation comment in .proto file."""

    def getListaCanciones(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getMetadatos(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getStreamAudio(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AudioServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'getListaCanciones': grpc.unary_unary_rpc_method_handler(
                    servicer.getListaCanciones,
                    request_deserializer=G4__Audio__pb2.listaCancionesS.FromString,
                    response_serializer=G4__Audio__pb2.listaCancionesR.SerializeToString,
            ),
            'getMetadatos': grpc.unary_unary_rpc_method_handler(
                    servicer.getMetadatos,
                    request_deserializer=G4__Audio__pb2.metadatosS.FromString,
                    response_serializer=G4__Audio__pb2.metadatosR.SerializeToString,
            ),
            'getStreamAudio': grpc.stream_stream_rpc_method_handler(
                    servicer.getStreamAudio,
                    request_deserializer=G4__Audio__pb2.cancionS.FromString,
                    response_serializer=G4__Audio__pb2.cancionR.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'G4_Audio.Audio', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('G4_Audio.Audio', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Audio(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def getListaCanciones(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/G4_Audio.Audio/getListaCanciones',
            G4__Audio__pb2.listaCancionesS.SerializeToString,
            G4__Audio__pb2.listaCancionesR.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def getMetadatos(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/G4_Audio.Audio/getMetadatos',
            G4__Audio__pb2.metadatosS.SerializeToString,
            G4__Audio__pb2.metadatosR.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def getStreamAudio(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/G4_Audio.Audio/getStreamAudio',
            G4__Audio__pb2.cancionS.SerializeToString,
            G4__Audio__pb2.cancionR.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
